package org.sih26042.coteacher.core.matching

import java.text.Normalizer

/**
 * Result of strict Ol Chiki script inspection and contamination analysis.
 */
data class ScriptValidationResult(
    val isValid: Boolean,
    val normalizedText: String,
    val olChikiRatio: Float,
    val detectedScripts: Set<String>,
    val contaminations: List<ScriptContamination>,
    val warnings: List<String>
)

data class ScriptContamination(
    val character: Char,
    val codepoint: String,
    val detectedScript: String,
    val index: Int
)

/**
 * Production script validator for Santali output.
 * 
 * Enforces:
 * 1. Unicode NFC normalization.
 * 2. Ol Chiki range verification (U+1C50 to U+1C7F).
 * 3. Detection and rejection of foreign script leakage:
 *    - Devanagari (U+0900..U+097F)
 *    - Bengali (U+0980..U+09FF)
 *    - Arabic (U+0600..U+06FF)
 *    - Latin (A-Z, a-z)
 *    - Zero-width and control characters (U+200B..U+200D, U+FEFF)
 * 4. Deterministic Ol Chiki -> Latin phonetic transliteration.
 */
object OlChikiScriptValidator {

    private val PUNCTUATION_AND_SPACE = setOf(
        ' ', '\t', '\n', '\r', '.', ',', '?', '!', '-', ':', ';', '—',
        '(', ')', '[', ']', '\'', '"', '/', '\\', '।', '॥',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
    )

    private val ZERO_WIDTH_CHARS = setOf(
        '\u200B', '\u200C', '\u200D', '\uFEFF', '\u00A0', '\u2028', '\u2029'
    )

    fun identifyScript(cp: Int): String = when (cp) {
        in 0x1C50..0x1C7F -> "Ol Chiki"
        in 0x0900..0x097F -> "Devanagari"
        in 0x0980..0x09FF -> "Bengali"
        in 0x0600..0x06FF -> "Arabic"
        in 0x0041..0x005A, in 0x0061..0x007A -> "Latin"
        else -> "Other"
    }

    /**
     * Validates a candidate Santali string generated by neural MT or user input.
     */
    fun validate(rawText: String): ScriptValidationResult {
        if (rawText.isBlank()) {
            return ScriptValidationResult(
                isValid = false,
                normalizedText = "",
                olChikiRatio = 0f,
                detectedScripts = emptySet(),
                contaminations = emptyList(),
                warnings = listOf("Input string is empty or blank")
            )
        }

        // 1. Strip non-printable control characters & Unicode NFC Normalization
        val cleaned = rawText.filter { (it.code !in 0x00..0x1F && it.code !in 0x7F..0x9F) || it == '\n' || it == '\t' || it == '\r' }.trim()
        val nfc = Normalizer.normalize(cleaned, Normalizer.Form.NFC)

        var olChikiCount = 0
        var totalLetters = 0
        val detectedScripts = mutableSetOf<String>()
        val contaminations = mutableListOf<ScriptContamination>()
        val warnings = mutableListOf<String>()

        for ((idx, ch) in nfc.withIndex()) {
            if (ch in ZERO_WIDTH_CHARS) {
                warnings.add("Zero-width character detected at index $idx (U+%04X)".format(ch.code))
                continue
            }

            if (ch in PUNCTUATION_AND_SPACE) {
                continue
            }

            val cp = ch.code
            val script = identifyScript(cp)
            detectedScripts.add(script)
            totalLetters++

            if (script == "Ol Chiki") {
                olChikiCount++
            } else {
                contaminations.add(
                    ScriptContamination(
                        character = ch,
                        codepoint = "U+%04X".format(cp),
                        detectedScript = script,
                        index = idx
                    )
                )
            }
        }

        val ratio = if (totalLetters > 0) olChikiCount.toFloat() / totalLetters else 0f
        val isValid = contaminations.isEmpty() && olChikiCount > 0

        if (contaminations.isNotEmpty()) {
            val scriptNames = contaminations.map { it.detectedScript }.distinct().joinToString(", ")
            warnings.add("Script contamination detected: Contains non-Ol-Chiki glyphs ($scriptNames)")
        }

        return ScriptValidationResult(
            isValid = isValid,
            normalizedText = nfc,
            olChikiRatio = ratio,
            detectedScripts = detectedScripts,
            contaminations = contaminations,
            warnings = warnings
        )
    }

    /**
     * Deterministic phonetic transliteration of Ol Chiki to Latin.
     */
    fun transliterateToLatin(olChikiText: String): String {
        val sb = StringBuilder()
        for (ch in olChikiText) {
            val latin = when (ch) {
                // Digits
                '᱐' -> "0"; '᱑' -> "1"; '᱒' -> "2"; '᱓' -> "3"; '᱔' -> "4"
                '᱕' -> "5"; '᱖' -> "6"; '᱗' -> "7"; '᱘' -> "8"; '᱙' -> "9"
                // Letters
                'ᱚ' -> "o"; 'ᱛ' -> "t"; 'ᱜ' -> "g"; 'ᱝ' -> "ng"; 'ᱞ' -> "l"
                'ᱟ' -> "a"; 'ᱠ' -> "k"; 'ᱡ' -> "j"; 'ᱢ' -> "m"; 'ᱣ' -> "w"
                'ᱤ' -> "i"; 'ᱥ' -> "s"; 'ᱦ' -> "h"; 'ᱧ' -> "ny"; 'ᱨ' -> "r"
                'ᱩ' -> "u"; 'ᱪ' -> "c"; 'ᱫ' -> "d"; 'ᱬ' -> "n"; 'ᱭ' -> "y"
                'ᱮ' -> "e"; 'ᱯ' -> "p"; 'ᱰ' -> "d"; 'ᱱ' -> "n"; 'ᱲ' -> "r"
                'ᱳ' -> "o"; 'ᱴ' -> "t"; 'ᱵ' -> "b"; 'ᱶ' -> "w"; 'ᱷ' -> "h"
                // Modifiers
                'ᱸ' -> "n"; 'ᱹ' -> "'"; 'ᱺ' -> ""; 'ᱻ' -> ""; 'ᱼ' -> ""; 'ᱽ' -> ""
                '᱾' -> "."; '᱿' -> ".."
                else -> ch.toString()
            }
            sb.append(latin)
        }
        return sb.toString().replace(Regex("\\s+"), " ").trim()
    }
}
