package org.sih26042.coteacher.core.model

/**
 * PHASE 5 — NIPUN/FLN Classroom Domain Models
 *
 * Strict separation of concerns:
 *  - ProvenanceState:     linguistic validation status (was this reviewed by a native speaker?)
 *  - MatchConfidence:     how confidently the ASR + PhraseMatcher recognised teacher speech
 *  - TranslationQuality:  how reliably the MT model produced output
 *
 * These MUST NOT be merged into one "confidence score".
 */

// ---------------------------------------------------------------------------
// Content provenance — mirrors pack-level states
// ---------------------------------------------------------------------------

enum class ContentProvenance {
    /** Reviewed and approved by a qualified native educator. */
    VERIFIED,
    /** System-generated or draft — pending native-speaker review. */
    PENDING_VALIDATION,
    /** Dynamically generated by on-device MT; presented with explicit badge. */
    MACHINE_GENERATED,
    /** Created or modified by the classroom teacher on-device. */
    TEACHER_CREATED,
    /** Confidence below threshold — teacher must confirm. */
    LOW_CONFIDENCE,
    /** Resource explicitly not available (model missing, pack missing, etc.). */
    UNAVAILABLE
}

// ---------------------------------------------------------------------------
// Domain: Grade / Subject / Learning Outcome
// ---------------------------------------------------------------------------

enum class GradeLevel(val displayLabel: String) {
    BALVATIKA("Balvatika (Pre-Grade 1)"),
    GRADE_1("Grade 1"),
    GRADE_2("Grade 2"),
    GRADE_3("Grade 3")
}

enum class SubjectDomain(val displayLabel: String, val icon: String) {
    FOUNDATIONAL_NUMERACY("Foundational Numeracy", "🔢"),
    FOUNDATIONAL_LITERACY("Foundational Literacy", "📖"),
    ORAL_LANGUAGE("Oral Language", "🗣️"),
    ENVIRONMENTAL_AWARENESS("Environmental Awareness", "🌿"),
    CLASSROOM_ROUTINE("Classroom Routine", "📋")
}

data class LearningOutcome(
    val outcomeId: String,
    val domain: SubjectDomain,
    val gradeLevel: GradeLevel,
    /** Short student-facing objective in Hindi */
    val objectiveHindi: String,
    /** Same objective in Santali Ol Chiki */
    val objectiveSantali: String,
    /** Latin transliteration for teacher pronunciation support */
    val objectiveLatin: String,
    val nipunCompetencyRef: String? = null,
    val provenance: ContentProvenance = ContentProvenance.PENDING_VALIDATION
)

// ---------------------------------------------------------------------------
// Domain: Lesson
// ---------------------------------------------------------------------------

data class Lesson(
    val lessonId: String,
    val title: String,
    val gradeLevel: GradeLevel,
    val domain: SubjectDomain,
    val learningOutcome: LearningOutcome,
    /** Key classroom phrases used during this lesson. IDs reference the phrase bank. */
    val phraseIds: List<String> = emptyList(),
    /** FLN vocab items featured in this lesson */
    val vocabularyIds: List<String> = emptyList(),
    /** Ordered list of activity IDs for this lesson */
    val activityIds: List<String> = emptyList(),
    /** Worksheet IDs for this lesson */
    val worksheetIds: List<String> = emptyList(),
    /** Estimated duration in minutes */
    val estimatedMinutes: Int = 20,
    val contentVersion: String = "1.0",
    val provenance: ContentProvenance = ContentProvenance.PENDING_VALIDATION,
    val isDemo: Boolean = false
)

// ---------------------------------------------------------------------------
// Domain: Activity (engine-driven, not hardcoded UI)
// ---------------------------------------------------------------------------

enum class ActivityType {
    /** Show an item, student taps the correct answer from picture options */
    PICTURE_SELECTION,
    /** Teacher says a word/phrase; student selects the matching number */
    NUMBER_SELECTION,
    /** Match left-column items to right-column items */
    MATCHING,
    /** Student selects Yes / No */
    YES_NO,
    /** Teacher leads call; students respond chorally */
    CHORAL_RESPONSE,
    /** Sequential items that need ordering */
    ORDERING,
    /** Tap the correct letter / shape from a grid */
    RECOGNITION_TAP
}

data class ActivityItem(
    val itemId: String,
    val activityId: String,
    /** Teacher instruction in Hindi */
    val promptHindi: String,
    /** Same instruction in Santali */
    val promptSantali: String,
    val promptLatin: String,
    val audioPath: String? = null,
    /** For selection-type activities */
    val options: List<String> = emptyList(),
    /** Correct option value (must exist in options) */
    val correctAnswer: String = "",
    /** Optional local asset path for picture activities */
    val visualAsset: String? = null
)

data class ClassroomActivity(
    val activityId: String,
    val title: String,
    val type: ActivityType,
    val gradeLevel: GradeLevel,
    val domain: SubjectDomain,
    val objectiveHindi: String,
    val objectiveSantali: String,
    val objectiveLatin: String = "",
    val items: List<ActivityItem>,
    val estimatedMinutes: Int = 5,
    val provenance: ContentProvenance = ContentProvenance.PENDING_VALIDATION,
    val contentVersion: String = "1.0"
)

// ---------------------------------------------------------------------------
// Domain: Activity state machine
// ---------------------------------------------------------------------------

sealed class ActivityState {
    object Idle : ActivityState()
    object Intro : ActivityState()
    data class Instruction(val item: ActivityItem) : ActivityState()
    data class AwaitingResponse(val item: ActivityItem) : ActivityState()
    data class Feedback(val item: ActivityItem, val wasCorrect: Boolean, val response: String) : ActivityState()
    object Complete : ActivityState()
}

// ---------------------------------------------------------------------------
// Domain: Session persistence
// ---------------------------------------------------------------------------

data class ClassSession(
    val sessionId: String = java.util.UUID.randomUUID().toString(),
    val lessonId: String,
    val languagePackId: String = "sat_1.0",
    val gradeLevel: String,
    val domain: String,
    val startTimeMs: Long = System.currentTimeMillis(),
    val endTimeMs: Long? = null,
    val completed: Boolean = false,
    val translationsUsed: Int = 0,
    val verifiedTranslations: Int = 0,
    val machineGeneratedTranslations: Int = 0,
    val deviceInfo: String = ""
)

data class ActivityAttempt(
    val attemptId: String = java.util.UUID.randomUUID().toString(),
    val sessionId: String,
    val activityId: String,
    val itemId: String,
    val response: String,
    val correct: Boolean,
    val timestampMs: Long = System.currentTimeMillis()
)

// ---------------------------------------------------------------------------
// Domain: Session summary
// ---------------------------------------------------------------------------

data class ActivitySummary(
    val activityId: String,
    val title: String,
    val totalItems: Int,
    val correctItems: Int,
    val completed: Boolean
) {
    val score: Float get() = if (totalItems > 0) correctItems.toFloat() / totalItems else 0f
}

data class SessionSummary(
    val session: ClassSession,
    val lessonTitle: String,
    val activitiesSummary: List<ActivitySummary>,
    val nextSuggestedLessonId: String? = null,
    val nextSuggestedLessonTitle: String? = null
) {
    val totalActivities: Int get() = activitiesSummary.size
    val completedActivities: Int get() = activitiesSummary.count { it.completed }
}

// ---------------------------------------------------------------------------
// Domain: Teacher content feedback
// ---------------------------------------------------------------------------

enum class ContentFeedbackType {
    TRANSLATION_WRONG,
    AUDIO_UNCLEAR,
    WORD_INAPPROPRIATE,
    WRONG_MEANING,
    SCRIPT_ISSUE,
    NEEDS_REVIEW,
    OTHER
}

data class TeacherContentFeedback(
    val feedbackId: String = java.util.UUID.randomUUID().toString(),
    val contentId: String,
    val contentType: String, // "PHRASE", "ACTIVITY", "WORKSHEET"
    val feedbackType: ContentFeedbackType,
    val notes: String = "",
    val timestampMs: Long = System.currentTimeMillis(),
    val syncStatus: String = "QUEUED_OFFLINE"
)

// ---------------------------------------------------------------------------
// Domain: Language pack availability (for UI display)
// ---------------------------------------------------------------------------

enum class LanguageAvailability {
    AVAILABLE,
    PARTIALLY_AVAILABLE,
    COMING_IN_FUTURE_PACK,
    UNAVAILABLE
}
